name: deploy

on:
  push:
    branches:
      - main  # 确保你的分支名是 main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          # 注意：这里需要你配置一个名为 GH_PAT 的 Secret，或者使用默认的 GITHUB_TOKEN
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 推送到你的网页仓库
          external_repository: yubailing666/yubailing666.github.io
          publish_branch: main
          publish_dir: ./public